### ISSUE TITLE
Error using rev pi nodes package after Node RED update

### ISSUE THREAD

**Issue by halcyon0606** [erminas/noderedrevpinodes-server#4]
Hello, 

I recently updated the node red version in my RevPi and immediately after the rev pi nodes server cannot be enabled anymore in the configuration settings. Is this due to an incompatibility due to the current version or is this actually some other underlying error? Would love some help on this.

**Comment by jgerlach-erminas** [comment]
Hi,
what do you mean by "configuration settings"? There is a known problem in the installation procedure (old Node Red version in the debian repo is marked as dependency) which is fixed in the upcoming release. If you like you can attach logs here for node red and the server to further analyse your problem:
$ node-red start
$ cat /usr/share/noderedrevpinodes-server/revpi-server.log

**Comment by halcyon0606** [comment]
By configuration settings, I meant the localhost web page where you can enable services and access applications such as PiCtory. But anyhow, since you say the issue is due to the dependency of the older version of node red and that this will be fixed in the upcoming release I think I will just wait for that. Thanks for the info and help!
